environment:
  my_version_number: 6.0.5          # ALSO CHANGE IN BUILD.GRADLE & INNO
  application_name: PasswordSaver   # ALSO CHANGE IN BUILD.GRADLE & INNO

version: $(my_version_number).{build}

skip_tags: true

configuration: Release

cache:
  - C:\Users\appveyor\.gradle

before_build:
  - 'curl -H "Authorization: token %download_token%" -H "Accept: application/vnd.github.v3.raw" -O -L "%download_link%/tandem-developer-certificate.pfx"'


build:
  verbosity: minimal

build_script:
  - del gradlew.bat
  - ren gradlew-appveyor.bat gradlew.bat
  - gradlew.bat jpackage --info --no-daemon -PbintrayUserName -PbintrayApiKey

for:
  - branches:
      only:
        - master

    after_build:
      - '"C:\Program Files (x86)\Inno Setup 6\iscc.exe" "/ssigntool=$qC:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe$q sign /f %APPVEYOR_BUILD_FOLDER%/tandem-developer-certificate.pfx /t http://timestamp.comodoca.com/authenticode /p $q%tandem_cert_password%$q /fd sha256 $f" /qp "Inno Config.iss"'

    artifacts:
      - path: /Installer/PasswordSaverV6.exe
        name: WinInstaller

    deploy:
      - provider: GitHub
        release: $(my_version_number)
        auth_token: # encrypted token:
          secure: HESVuhwKdUbPpbBsQrWslB7GYNy5r03/MN/enpu7UWbY886bOE+EpbEFwAVMrtLO
        artifact: WinInstaller
        draft: false
        prerelease: false
        force_update: false
        on:
          branch: master
